/*
* WARNING: Do not change this file!
* This file is automatically generated during build time by RollupJS and will be removed on every rebuild.
* See rollup.config.js in the root folder of this project for more information.
*/

module.exports = [
  {
    "id": "overview",
    "title": "Overview",
    "link": false,
    "children": [
      {
        "id": "nymeainaction",
        "title": "Nymea in action",
        "link": true,
        "children": [],
      },
      {
        "id": "integrations",
        "title": "Integrations",
        "link": true,
        "children": [],
      },
      {
        "id": "features",
        "title": "Features",
        "link": true,
        "children": [],
      },
      {
        "id": "license",
        "title": "License",
        "link": true,
        "children": [],
      },
      {
        "id": "roadmap",
        "title": "Roadmap",
        "link": true,
        "children": [],
      },
      {
        "id": "faq",
        "title": "Frequently asked questions",
        "link": true,
        "children": [],
      },
      {
        "id": "contribute",
        "title": "Contribute",
        "link": true,
        "children": [],
      },
    ],
  },
  {
    "id": "developers",
    "title": "Developers",
    "link": false,
    "children": [
      {
        "id": "index",
        "title": "Introduction",
        "link": true,
        "children": [],
      },
      {
        "id": "build-env",
        "title": "Build environment",
        "link": true,
        "children": [],
      },
      {
        "id": "build-nymea",
        "title": "Building nymea",
        "link": true,
        "children": [],
      },
      {
        "id": "qtcreator",
        "title": "Developing with QtCreator",
        "link": true,
        "children": [],
      },
      {
        "id": "write-plugins",
        "title": "Plugin development",
        "link": true,
        "children": [],
      },
      {
        "id": "integrations",
        "title": "Integration plugins",
        "link": false,
        "children": [
          {
            "id": "getting-started-integration",
            "title": "Getting started",
            "link": true,
            "children": [],
          },
          {
            "id": "thing-setup",
            "title": "Things setup",
            "link": true,
            "children": [],
          },
          {
            "id": "events-actions-states",
            "title": "Events, actions and states",
            "link": true,
            "children": [],
          },
          {
            "id": "browsing",
            "title": "Browsing things",
            "link": true,
            "children": [],
          },
          {
            "id": "interfaces",
            "title": "Interfaces",
            "link": true,
            "children": [],
          },
          {
            "id": "plugin-json",
            "title": "The plugin JSON file",
            "link": true,
            "children": [],
          },
          {
            "id": "plugin-cpp",
            "title": "The plugin code (C++/Qt)",
            "link": true,
            "children": [],
          },
          {
            "id": "plugin-js",
            "title": "The plugin code (JS)",
            "link": true,
            "children": [],
          },
          {
            "id": "building-testing",
            "title": "Building & testing",
            "link": true,
            "children": [],
          },
          {
            "id": "tutorial-integration-cpp",
            "title": "Tutorial (C++/Qt)",
            "link": true,
            "children": [],
          },
          {
            "id": "tutorial-integration-js",
            "title": "Tutorial (JS)",
            "link": true,
            "children": [],
          },
        ],
      },
      {
        "id": "clients",
        "title": "Client development",
        "link": false,
        "children": [
          {
            "id": "index",
            "title": "Introduction",
            "link": true,
            "children": [],
          },
          {
            "id": "nymea-app-lib",
            "title": "C++/Qt/QML",
            "link": true,
            "children": [],
          },
          {
            "id": "nymea-cli-dev",
            "title": "Python",
            "link": true,
            "children": [],
          },
        ],
      },
    ]
  },
  {
    "id": "users",
    "title": "Users",
    "link": false,
    "children": [
      {
        "id": "installation",
        "title": "Installation",
        "link": false,
        "children": [
          {
            "id": "gettingstarted",
            "title": "Getting started",
            "link": true,
            "children": [],
          },
          {
            "id": "core",
            "title": "nymea:core",
            "link": true,
            "children": [],
          },
          {
            "id": "app",
            "title": "nymea:app",
            "link": true,
            "children": [],
          },
        ],
      },
      {
        "id": "usage",
        "title": "Usage",
        "link": false,
        "children": [
          {
            "id": "firststeps",
            "title": "First steps",
            "link": true,
            "children": [],
          },
          {
            "id": "things",
            "title": "Connecting things",
            "link": true,
            "children": [],
          },
          {
            "id": "rules",
            "title": "Smart rules",
            "link": true,
            "children": [],
          },
          {
            "id": "scripting",
            "title": "Scripting",
            "link": true,
            "children": [],
          },
          {
            "id": "configuration",
            "title": "Configuration",
            "link": true,
            "children": [],
          },
          {
            "id": "advanced-configuration",
            "title": "Advanced configuration",
            "link": true,
            "children": [],
          },
        ]
      },
    ],
  },
];
