/*
* WARNING: Do not change this file!
* This file is automatically generated during build time by RollupJS and will be removed on every rebuild.
* See rollup.config.js in the root folder of this project for more information.
*/

module.exports = [
  {
    "id": "developers",
    "title": "Developers",
    "link": false,
    "children": [
      {
        "id": "build",
        "title": "Build",
        "link": false,
        "children": []
      }
    ]
  }
];