#!/bin/bash

branch="master"
if [ -n $1 ]; then
  branch=$1
fi

echo "Building docs from branches $branch"

./generate-interfaces-list.py $branch
./generate-plugins-list.py $branch
./generate-jsonrpc-api.py $branch
./generate-menu.py
